base_dataset_name: "epr-labs/maestro-sustain-v2"
extra_datasets:
  - 'epr-labs/maestro-augmented'
  - 'epr-labs/giant-midi-augmented'
  - 'epr-labs/piano-midi-de-augmented'
  - 'epr-labs/pianofor-ai-augmented'
  - 'epr-labs/imslp-augmented'
pause_detection_threshold: 4
augmentation:
  speed_change_factors: []
  max_pitch_shift: 0
