base_dataset_name: "roszcz/maestro-sustain-v2"
extra_datasets:
  - 'epr-labs/maestro-augmented'
  - 'epr-labs/giant-midi-augmented'
  - 'epr-labs/pianofor-ai-augmented'
  - 'epr-labs/imslp-augmented'
  - 'epr-labs/pijamia-midi-v1'
  - 'epr-labs/lakh-lmd-full'
  - 'epr-labs/vgmidi'
  - 'epr-labs/jsb-chorales'
  - 'epr-labs/piano-midi-de'
  - 'epr-labs/atepp-1.1-sustain-v2'
  - 'epr-labs/music-net'
pause_detection_threshold: 4
augmentation:
  speed_change_factors: []
  max_pitch_shift: 0
