list:
  - "above_median_prediction"  # Pitch tasks
  - "below_median_prediction"
  - "above_low_quartile_prediction"
  - "above_high_quartile_prediction"
  - "below_low_quartile_prediction"
  - "below_high_quartile_prediction"
  - "middle_quartiles_prediction"
  - "extreme_quartiles_prediction"
  - "loud_prediction"  # Velocity tasks
  - "very_soft_prediction"
  - "very_loud_prediction"
  - "soft_prediction"
  - "moderate_velocity_prediction"
  - "extreme_velocity_prediction"
