n_layer: 36
n_head: 20
n_embd: 1280
dropout: 0.0  # for pretraining 0 is good, for finetuning try 0.1+
bias: false  # do we use bias inside LayerNorm and Linear layers?
block_size: ${data.sequence_length}
